### ISSUE TITLE
mdslw keeps indenting lists

### ISSUE THREAD

**Issue by grimm26** [razziel89/mdslw#24]
First it splits the sentences of unordered list elements just fine. Subsequently, it keeps indenting the additional sentences for the list elements.

```
❯ cat test.md
- foo this is the thing. I like to go.
- yay. No way.
❯ ~/.local/share/nvim/mason/bin/mdslw --version
mdslw 0.12.3
❯ ~/.local/share/nvim/mason/bin/mdslw --max-width 0 --report diff-meyers test.md
--- original:test.md
+++ processed:test.md
@@ -1,2 +1,4 @@
-- foo this is the thing. I like to go.
-- yay. No way.
+- foo this is the thing.
+  I like to go.
+- yay.
+  No way.

❯ ~/.local/share/nvim/mason/bin/mdslw --max-width 0 --report diff-meyers test.md
--- original:test.md
+++ processed:test.md
@@ -1,4 +1,4 @@
 - foo this is the thing.
-  I like to go.
+    I like to go.
 - yay.
-  No way.
+    No way.

❯ ~/.local/share/nvim/mason/bin/mdslw --max-width 0 --report diff-meyers test.md
--- original:test.md
+++ processed:test.md
@@ -1,4 +1,4 @@
 - foo this is the thing.
-    I like to go.
+      I like to go.
 - yay.
-    No way.
+      No way.

```

**Comment by razziel89** [comment]
Thanks a lot for the bug report @grimm26! That's a nice use of the diff feature.

A could reproduce the behaviour, and it's certainly not intended to work that way. The bug seems to occur only when setting a max width of 0. Personally, I never use mdslw that way, which is probably why the bug went undetected for so long.

In any event, I'm currently only on mobile, but I'll try to fix it in the coming week. As a temporary workaround, I would like to suggest specifying a very large value for the max width. Something like 1000 or even 1 million should work as it is likely larger than the number of characters in any one sentence.

**Comment by razziel89** [comment]
This PR was closed automatically by merging PR #25. I'm again only on mobile but I intend to make a release containing the bugfix tomorrow.

**Comment by razziel89** [comment]
Version 0.12.4 has been released that fixes this bug, as far as I can tell. Can you please confirm, if time permits, @grimm26?

**Comment by grimm26** [comment]
@razziel89 It seems to have fixed the issue. Thanks!

```
❯ cat test.md
- foo this is the thing. I like to go.
❯ ~/.local/share/nvim/mason/bin/mdslw --version
mdslw 0.12.4
❯ ~/.local/share/nvim/mason/bin/mdslw --max-width 0 --report diff-meyers test.md
--- original:test.md
+++ processed:test.md
@@ -1 +1,2 @@
-- foo this is the thing. I like to go.
+- foo this is the thing.
+  I like to go.

❯ ~/.local/share/nvim/mason/bin/mdslw --max-width 0 --report diff-meyers test.md
❯ cat test.md
- foo this is the thing.
  I like to go.                                                          
```
